files:
  - source: /en/**/*.*
    translation: /%two_letters_code%/**/%original_file_name%
    ignore:
      - /en/blog/**/*.*
  - source: /_data/en/**/*.*
    translation: /_data/%two_letters_code%/**/%original_file_name%