files:
  - source: /en/**/*.*
    ignore:
      - /en/blog/**/*.*
    translation: /%two_letters_code%/**/%original_file_name%
  - source: /_data/en/**/*.*
    translation: /_data/%two_letters_code%/**/%original_file_name%
preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
